### ISSUE TITLE
Rajouter des fonctions sous forme de boutons

### ISSUE THREAD

**Issue by Azurency** [Azurency/puit-canadien-web#29]
## Rajouter des fonctions sous forme de boutons

Avoir la possibilité de remettre à zéro le zoom de la vue 3D en cliquant sur un bouton (ce qui induit de parler de l'`index` vers l'`iframe`).

Pourquoi pas avoir des boutons du type `1 semaine`, `1 mois`, `1 année` lors de la sélection de la plage d'étude ?

Ajouter des boutons ou onglets pour switcher entre les différentes vues 3D (voir #27), et entre les différents graphes (voir #28).

**Comment by adrien-jousse** [comment]
Pour le bouton de l'index vers l'ifram c'est fait
