### ISSUE TITLE
Mettre à l'échelle les vues 3D

### ISSUE THREAD

**Issue by adrien-jousse** [Azurency/puit-canadien-web#39]
Corriger la position de certaines corbeilles et sondes afin que cette dernière soit cohérente par rapport à la réalité.

**Comment by Azurency** [comment]
Je pense pas qu'on va le faire cette année, peut-être pour les nouvelles vues que l'on va créer pour le forage qu'ils ont fait. 
Mais on retouchera a la 3D actuelle que si on a du temps a perdre _(et puis il ira pas vérifier)_

**Comment by adrien-jousse** [comment]
Ok pour la nouvelle vue.
Pour la vue actuelle, faudrai juste corriger la position des rouges et vertes sur la gauche et ça passera.
