### ISSUE TITLE
Liste verticale pour les sondes sélectionnées

### ISSUE THREAD

**Issue by adrien-jousse** [Azurency/puit-canadien-web#43]
Positionner les sondes sélectionnées sous forme d'une liste verticale plutôt qu'une liste horizontale sous le graphe.

**Comment by Azurency** [comment]
Liste verticale ? Je pense pas que se soit judicieux, ça prendra beaucoup trop de place si on a 10-20 sondes sélectionnées !

**Comment by adrien-jousse** [comment]
Je suis d'accord, mais c'est seulement le cas si on laisse une seule colonne.
Si on met 3-4 colonnes, de 4-5 sondes ça ira, et ça sera plus agréable à l'oeil qu'un enchainement horizontal.
